default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "chep171615") %>

development:
  <<: *default
  database: ministore-backend_development

test:
  <<: *default
  database: ministore-backend_test

production:
  <<: *default
  database: ministore-backend_production
  username: ministore-backend
  password: <%= ENV['ministore-backend_DATABASE_PASSWORD'] %>
